server:
  port: 8803
spring:
  application:
    name: center8803   #配置中心
  cloud:
    stream:
      binders:
        defaultRabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: 192.168.32.128
                port: 5672
                username: guest
                password: guest
      bindings:
        input:
          default-binder: defaultRabbit
          destination: studyExchange
          content-type: application/json
          group: qyc

eureka:
  client:
    register-with-eureka: true  #注册
    fetch-registry: true  #检测
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: send-8803.com
    prefer-ip-address: true