server:
  port: 9527

spring:
  application:
    name: cloud-getway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  #开启动态路由，利用微服务名进行路由
      routes:
        - id: payment_routh   #路由的ID,没有固定规则但要求唯一，配合服务名
#          uri: http://localhost:8001  #匹配后提供服务的路由地址
          uri: lb://order-81
          predicates:
            - Path=/openfeign/pay/**    #断言  匹配路径进行路由
            - After=2020-05-10T18:19:40.987+08:00[Asia/Shanghai]   #时间


eureka:
  instance:
    hostname: cloud-getway-service
  client:
    register-with-eureka: true  #注册
    fetch-registry: true  #检测
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka